In [1]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [2]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\KIIT\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [4]:
fake_news=pd.read_csv("fake-prayash.csv")
true_news=pd.read_csv("True-prayash.csv")

In [5]:
fake_news['label'] = 0
true_news['label'] = 1

In [6]:
news_dataset = pd.concat([fake_news, true_news], axis =0 )
news_dataset.head()

author                      published  \
0     Barracuda Brigade  2016-10-26T21:41:00.000+03:00   
1  reasoning with facts  2016-10-29T08:47:11.259+03:00   
2     Barracuda Brigade  2016-10-31T01:41:49.479+02:00   
3                Fed Up  2016-11-01T05:22:00.000+02:00   
4                Fed Up  2016-11-01T21:56:00.000+02:00   

                                               title  \
0  muslims busted they stole millions in govt ben...   
1  re why did attorney general loretta lynch plea...   
2  breaking weiner cooperating with fbi on hillar...   
3  pin drop speech by father of daughter kidnappe...   
4  fantastic trumps  point plan to reform healthc...   

                                                text language  \
0  print they should pay all the back all the mon...  english   
1  why did attorney general loretta lynch plead t...  english   
2  red state  \nfox news sunday reported this mor...  english   
3  email kayla mueller was a prisoner and torture...  english   
4  email healthcare reform to make america great ...  english   

              site_url                                       main_img_url  \
0  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
1  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
2  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
3  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   
4  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   

   type  label                            title_without_stopwords  \
0  bias      0        muslims busted stole millions govt benefits   
1  bias      0         attorney general loretta lynch plead fifth   
2  bias      0  breaking weiner cooperating fbi hillary email ...   
3  bias      0  pin drop speech father daughter kidnapped kill...   
4  bias      0  fantastic trumps point plan reform healthcare ...   

                              text_without_stopwords  hasImage subject date  
0  print pay back money plus interest entire fami...       1.0     NaN  NaN  
1  attorney general loretta lynch plead fifth bar...       1.0     NaN  NaN  
2  red state fox news sunday reported morning ant...       1.0     NaN  NaN  
3  email kayla mueller prisoner tortured isis cha...       1.0     NaN  NaN  
4  email healthcare reform make america great sin...       1.0     NaN  NaN

In [7]:
news_dataset = news_dataset.sample(len(news_dataset))
news_dataset.head()

author published                                              title  \
18784    NaN       NaN  Merkel's conservatives warned not to close off...   
13898    NaN       NaN  EU's Juncker says Dec. 4 meeting with May will...   
7735     NaN       NaN  Trump gains on Clinton despite furor over wome...   
1622     NaN       NaN  Kremlin 'deeply concerned' by rising tension o...   
16592    NaN       NaN  Argentina midterm vote leaves Peronism divided...   

                                                    text language site_url  \
18784  MUNICH, Germany (Reuters) - German Chancellor ...      NaN      NaN   
13898  BRUSSELS (Reuters) - The president of the Euro...      NaN      NaN   
7735   NEW YORK (Reuters) - Donald Trump gained on Hi...      NaN      NaN   
1622   MOSCOW (Reuters) - Moscow is deeply concerned ...      NaN      NaN   
16592  BUENOS AIRES (Reuters) - The victory of Argent...      NaN      NaN   

      main_img_url type  label title_without_stopwords text_without_stopwords  \
18784          NaN  NaN      1                     NaN                    NaN   
13898          NaN  NaN      1                     NaN                    NaN   
7735           NaN  NaN      1                     NaN                    NaN   
1622           NaN  NaN      1                     NaN                    NaN   
16592          NaN  NaN      1                     NaN                    NaN   

       hasImage       subject                 date  
18784       NaN     worldnews  September 28, 2017   
13898       NaN     worldnews   November 24, 2017   
7735        NaN  politicsNews    October 21, 2016   
1622        NaN  politicsNews  September 22, 2017   
16592       NaN     worldnews    October 24, 2017

In [8]:
news_dataset.shape

(23513, 14)

In [9]:
news_dataset.isnull().sum()

author                     21417
published                  21417
title                          0
text                          46
language                   21418
site_url                   21418
main_img_url               21418
type                       21418
label                          0
title_without_stopwords    21419
text_without_stopwords     21467
hasImage                   21418
subject                     2096
date                        2096
dtype: int64

In [10]:
print(news_dataset['title'])

18784    Merkel's conservatives warned not to close off...
13898    EU's Juncker says Dec. 4 meeting with May will...
7735     Trump gains on Clinton despite furor over wome...
1622     Kremlin 'deeply concerned' by rising tension o...
16592    Argentina midterm vote leaves Peronism divided...
                               ...                        
4948     Trump's pick to lead U.S. CFTC unveils major n...
5025     The Trump presidency on March 9 at 9:49 p.m. E...
6580     Trump aide named to lead White House communica...
2281     In Afghan review, Trump's frustration carries ...
8062     Obama to veto September 11 lawsuit bill by Fri...
Name: title, Length: 23513, dtype: object


In [11]:
port_stem = PorterStemmer()

In [12]:
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]',' ',content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content

In [13]:
news_dataset['title'] = news_dataset['title'].apply(stemming)
print(news_dataset['title'])

18784              merkel conserv warn close coalit option
13898    eu juncker say dec meet may show brexit progre...
7735     trump gain clinton despit furor women elect co...
1622     kremlin deepli concern rise tension korean pen...
16592    argentina midterm vote leav peron divid leader...
                               ...                        
4948     trump pick lead u cftc unveil major new polici...
5025                    trump presid march p est march gmt
6580     trump aid name lead white hous commun say take...
2281     afghan review trump frustrat carri echo obama ...
8062     obama veto septemb lawsuit bill friday white hous
Name: title, Length: 23513, dtype: object


In [14]:
x = news_dataset['title'].values
y = news_dataset['label'].values

In [15]:
print(x)

['merkel conserv warn close coalit option'
 'eu juncker say dec meet may show brexit progress made'
 'trump gain clinton despit furor women elect comment' ...
 'trump aid name lead white hous commun say take job'
 'afghan review trump frustrat carri echo obama year'
 'obama veto septemb lawsuit bill friday white hous']


In [16]:
print(y)

[1 1 1 ... 1 1 1]


In [17]:
y.shape

(23513,)

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30)

In [19]:
x_train

array(['franc skip winter game secur assur',
       'smaller eu state need stronger voic brussel say czech elect favorit',
       'unforc error miscalcul end bush white hous hope', ...,
       'snub feder reserv nomine warn trump struggl fill key post',
       'trump visit fbi headquart msnbc',
       'u state could set self drive car rule republican plan'],
      dtype=object)

In [20]:
vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [21]:
print(xv_train)

  (0, 460)	0.4457812381970106
  (0, 7249)	0.2920515776678631
  (0, 3258)	0.41434687791218006
  (0, 9088)	0.47218196479444047
  (0, 7510)	0.4668282657112995
  (0, 3151)	0.32158543324212235
  (1, 2896)	0.36858825786299776
  (1, 2512)	0.19598388318680438
  (1, 1912)	0.3226370097895283
  (1, 7139)	0.13184612321241587
  (1, 1046)	0.339909986796702
  (1, 8877)	0.3358753383063789
  (1, 7899)	0.3611793171587242
  (1, 5432)	0.26115409100358233
  (1, 7794)	0.19115502341571797
  (1, 2696)	0.20833322300129645
  (1, 7561)	0.44419477509712996
  (2, 3825)	0.27802753901422234
  (2, 3843)	0.18562013536125718
  (2, 9052)	0.2115289358858751
  (2, 1096)	0.3516725698597835
  (2, 2576)	0.2717299703004813
  (2, 5163)	0.4705438421127004
  (2, 2661)	0.4290570960201553
  (2, 8614)	0.49039686992724324
  :	:
  (16455, 6277)	0.36141823583172794
  (16456, 7906)	0.3536817276341402
  (16456, 2911)	0.31700982689756924
  (16456, 7589)	0.41195387276087786
  (16456, 6209)	0.2834615831543131
  (16456, 5534)	0.284998216497

###  Decision Tree Classification

In [22]:
from sklearn.tree import DecisionTreeClassifier

In [23]:
DT = DecisionTreeClassifier()
DT.fit(xv_train, y_train)

DecisionTreeClassifier()

In [24]:
pred_dt = DT.predict(xv_test)

In [25]:
DT.score(xv_test, y_test)

0.9277005954068613

In [26]:
from sklearn.metrics import classification_report

In [27]:
print(classification_report(y_test, pred_dt))

              precision    recall  f1-score   support

           0       0.59      0.62      0.60       627
           1       0.96      0.96      0.96      6427

    accuracy                           0.93      7054
   macro avg       0.78      0.79      0.78      7054
weighted avg       0.93      0.93      0.93      7054



In [28]:
y_pred = DT.predict(xv_test)

In [29]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred)) 

[[ 390  237]
 [ 273 6154]]


In [30]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))        #error
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.07229940459313865
Mean Squared Error: 0.07229940459313865
Root Mean Squared Error: 0.26888548602172385


###  Naive Bayes using Bernoulli naive bayes

In [31]:
from sklearn.naive_bayes import BernoulliNB

In [32]:
BNB = BernoulliNB()

In [33]:
BNB.fit(xv_train, y_train)

BernoulliNB()

In [34]:
pred_bnb = BNB.predict(xv_test)
BNB.score(xv_test,y_test)
print(classification_report(y_test, pred_bnb)) 

              precision    recall  f1-score   support

           0       0.90      0.33      0.49       627
           1       0.94      1.00      0.97      6427

    accuracy                           0.94      7054
   macro avg       0.92      0.67      0.73      7054
weighted avg       0.94      0.94      0.92      7054



In [35]:
print(confusion_matrix(y_test, pred_bnb)) 

[[ 210  417]
 [  24 6403]]


In [36]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_bnb))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_bnb))                 #error
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_bnb)))

Mean Absolute Error: 0.06251772044230224
Mean Squared Error: 0.06251772044230224
Root Mean Squared Error: 0.2500354383728479


###  K nearest neighbor

In [37]:
from sklearn.neighbors import KNeighborsClassifier

In [38]:
ng = KNeighborsClassifier()
ng.fit(xv_test, y_test)

KNeighborsClassifier()

In [39]:
pred_knn = ng.predict(xv_test)

In [40]:
ng.score(xv_test,y_test)

0.13821944995747093

In [41]:
print(classification_report(y_test, pred_knn))      # Precision , Recall , F-measure , Accuracy

              precision    recall  f1-score   support

           0       0.09      1.00      0.17       627
           1       1.00      0.05      0.10      6427

    accuracy                           0.14      7054
   macro avg       0.55      0.53      0.14      7054
weighted avg       0.92      0.14      0.11      7054



In [42]:
print(confusion_matrix(y_test, pred_knn))                  #confusion Matrix

[[ 626    1]
 [6078  349]]


In [43]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_knn))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_knn))                 #error
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_knn)))

Mean Absolute Error: 0.8617805500425291
Mean Squared Error: 0.8617805500425291
Root Mean Squared Error: 0.9283213614059137


### Support Vector Machine

In [44]:
from sklearn.svm import LinearSVC

In [45]:
ls = LinearSVC()

In [46]:
ls.fit(xv_test, y_test)

LinearSVC()

In [47]:
pred_ls = ls.predict(xv_test)

In [48]:
ls.score(xv_test,y_test)

0.994754749078537

In [49]:
print(classification_report(y_test, pred_ls))      # Precision , Recall , F-measure , Accuracy

              precision    recall  f1-score   support

           0       0.99      0.95      0.97       627
           1       0.99      1.00      1.00      6427

    accuracy                           0.99      7054
   macro avg       0.99      0.97      0.98      7054
weighted avg       0.99      0.99      0.99      7054



In [50]:
print(confusion_matrix(y_test, pred_ls))                  #confusion Matrix

[[ 594   33]
 [   4 6423]]


In [51]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_ls))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_ls))                 #error
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_ls)))

Mean Absolute Error: 0.0052452509214629996
Mean Squared Error: 0.0052452509214629996
Root Mean Squared Error: 0.07242410456100233


### ANN (Artificial Neural Network)

In [52]:
from sklearn.neural_network import MLPClassifier

In [53]:
ann = MLPClassifier()

In [54]:
ann.fit(xv_test, y_test)

MLPClassifier()

In [55]:
pred_ann = ann.predict(xv_test)

In [56]:
ann.score(xv_test,y_test)

1.0

In [57]:
print(classification_report(y_test, pred_ann))      # Precision , Recall , F-measure , Accuracy

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       627
           1       1.00      1.00      1.00      6427

    accuracy                           1.00      7054
   macro avg       1.00      1.00      1.00      7054
weighted avg       1.00      1.00      1.00      7054



In [58]:
print(confusion_matrix(y_test, pred_ann))                  #confusion Matrix

[[ 627    0]
 [   0 6427]]


In [59]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_ann))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_ann))                 #error
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_ann)))

Mean Absolute Error: 0.0
Mean Squared Error: 0.0
Root Mean Squared Error: 0.0
