In [45]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics
import re
import string

In [4]:
fake_news=pd.read_csv("news_articles.csv")
true_news=pd.read_csv("True1.csv")

In [5]:
fake_news.head(10)

author                      published  \
0     Barracuda Brigade  2016-10-26T21:41:00.000+03:00   
1  reasoning with facts  2016-10-29T08:47:11.259+03:00   
2     Barracuda Brigade  2016-10-31T01:41:49.479+02:00   
3                Fed Up  2016-11-01T05:22:00.000+02:00   
4                Fed Up  2016-11-01T21:56:00.000+02:00   
5     Barracuda Brigade  2016-11-02T16:31:28.550+02:00   
6                Fed Up  2016-11-04T19:40:00.000+02:00   
7                Fed Up  2016-11-05T01:19:00.000+02:00   
8                Fed Up  2016-11-06T23:54:00.000+02:00   
9                Fed Up  2016-11-07T02:43:00.000+02:00   

                                               title  \
0  muslims busted they stole millions in govt ben...   
1  re why did attorney general loretta lynch plea...   
2  breaking weiner cooperating with fbi on hillar...   
3  pin drop speech by father of daughter kidnappe...   
4  fantastic trumps  point plan to reform healthc...   
5  hillary goes absolutely berserk on protester a...   
6  breaking nypd ready to make arrests in weiner ...   
7  wow whistleblower tells chilling story of mass...   
8  breaking clinton clearedwas this a coordinated...   
9  evil hillary supporters yell fck trumpburn tru...   

                                                text language  \
0  print they should pay all the back all the mon...  english   
1  why did attorney general loretta lynch plead t...  english   
2  red state  \nfox news sunday reported this mor...  english   
3  email kayla mueller was a prisoner and torture...  english   
4  email healthcare reform to make america great ...  english   
5  print hillary goes absolutely berserk she expl...  english   
6  breaking nypd ready to make arrests in weiner ...  english   
7  breaking nypd ready to make arrests in weiner ...  english   
8  limbaugh said that the revelations in the wiki...  english   
9  email \nthese people are sick and evil they wi...  english   

              site_url                                       main_img_url  \
0  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
1  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
2  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
3  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   
4  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   
5  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/11/Fu...   
6  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   
7  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   
8  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   
9  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   

   type label                            title_without_stopwords  \
0  bias  Real        muslims busted stole millions govt benefits   
1  bias  Real         attorney general loretta lynch plead fifth   
2  bias  Real  breaking weiner cooperating fbi hillary email ...   
3  bias  Real  pin drop speech father daughter kidnapped kill...   
4  bias  Real  fantastic trumps point plan reform healthcare ...   
5  bias  Real  hillary goes absolutely berserk protester rall...   
6  bias  Real  breaking nypd ready make arrests weiner casehi...   
7  bias  Real  wow whistleblower tells chilling story massive...   
8  bias  Real  breaking clinton clearedwas coordinated last m...   
9  bias  Real  evil hillary supporters yell fck trumpburn tru...   

                              text_without_stopwords  hasImage  
0  print pay back money plus interest entire fami...       1.0  
1  attorney general loretta lynch plead fifth bar...       1.0  
2  red state fox news sunday reported morning ant...       1.0  
3  email kayla mueller prisoner tortured isis cha...       1.0  
4  email healthcare reform make america great sin...       1.0  
5  print hillary goes absolutely berserk explodes...      

In [6]:
true_news.head(10)

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   
5  White House, Congress prepare for talks on spe...   
6  Trump says Russia probe will be fair, but time...   
7  Factbox: Trump on Twitter (Dec 29) - Approval ...   
8         Trump on Twitter (Dec 28) - Global Warming   
9  Alabama official to certify Senator-elect Jone...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   
5  WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...  politicsNews   
6  WEST PALM BEACH, Fla (Reuters) - President Don...  politicsNews   
7  The following statements were posted to the ve...  politicsNews   
8  The following statements were posted to the ve...  politicsNews   
9  WASHINGTON (Reuters) - Alabama Secretary of St...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017   
5  December 29, 2017   
6  December 29, 2017   
7  December 29, 2017   
8  December 29, 2017   
9  December 28, 2017

In [7]:
fake_news['class'] = 0
true_news['class'] = 1

In [8]:
fake_news.shape,true_news.shape

((2096, 13), (21417, 5))

In [9]:
marge = pd.concat([fake_news, true_news], axis =0 )
marge.head(10)

author                      published  \
0     Barracuda Brigade  2016-10-26T21:41:00.000+03:00   
1  reasoning with facts  2016-10-29T08:47:11.259+03:00   
2     Barracuda Brigade  2016-10-31T01:41:49.479+02:00   
3                Fed Up  2016-11-01T05:22:00.000+02:00   
4                Fed Up  2016-11-01T21:56:00.000+02:00   
5     Barracuda Brigade  2016-11-02T16:31:28.550+02:00   
6                Fed Up  2016-11-04T19:40:00.000+02:00   
7                Fed Up  2016-11-05T01:19:00.000+02:00   
8                Fed Up  2016-11-06T23:54:00.000+02:00   
9                Fed Up  2016-11-07T02:43:00.000+02:00   

                                               title  \
0  muslims busted they stole millions in govt ben...   
1  re why did attorney general loretta lynch plea...   
2  breaking weiner cooperating with fbi on hillar...   
3  pin drop speech by father of daughter kidnappe...   
4  fantastic trumps  point plan to reform healthc...   
5  hillary goes absolutely berserk on protester a...   
6  breaking nypd ready to make arrests in weiner ...   
7  wow whistleblower tells chilling story of mass...   
8  breaking clinton clearedwas this a coordinated...   
9  evil hillary supporters yell fck trumpburn tru...   

                                                text language  \
0  print they should pay all the back all the mon...  english   
1  why did attorney general loretta lynch plead t...  english   
2  red state  \nfox news sunday reported this mor...  english   
3  email kayla mueller was a prisoner and torture...  english   
4  email healthcare reform to make america great ...  english   
5  print hillary goes absolutely berserk she expl...  english   
6  breaking nypd ready to make arrests in weiner ...  english   
7  breaking nypd ready to make arrests in weiner ...  english   
8  limbaugh said that the revelations in the wiki...  english   
9  email \nthese people are sick and evil they wi...  english   

              site_url                                       main_img_url  \
0  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
1  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
2  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
3  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   
4  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   
5  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/11/Fu...   
6  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   
7  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   
8  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   
9  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   

   type label                            title_without_stopwords  \
0  bias  Real        muslims busted stole millions govt benefits   
1  bias  Real         attorney general loretta lynch plead fifth   
2  bias  Real  breaking weiner cooperating fbi hillary email ...   
3  bias  Real  pin drop speech father daughter kidnapped kill...   
4  bias  Real  fantastic trumps point plan reform healthcare ...   
5  bias  Real  hillary goes absolutely berserk protester rall...   
6  bias  Real  breaking nypd ready make arrests weiner casehi...   
7  bias  Real  wow whistleblower tells chilling story massive...   
8  bias  Real  breaking clinton clearedwas coordinated last m...   
9  bias  Real  evil hillary supporters yell fck trumpburn tru...   

                              text_without_stopwords  hasImage  class subject  \
0  print pay back money plus interest entire fami...       1.0      0     NaN   
1  attorney general loretta lynch plead fifth bar...       1.0      0     NaN   
2  red state fox news sunday reported morning ant...       1.0      0     NaN   
3  email kayla mueller prisoner tortured isis cha...       1.0      0     NaN   
4  email healthcare reform make america gre

In [17]:
marge.columns

Index(['author', 'published', 'title', 'text', 'language', 'site_url',
       'main_img_url', 'type', 'label', 'title_without_stopwords',
       'text_without_stopwords', 'hasImage', 'class', 'subject', 'date'],
      dtype='object')

In [18]:
marge.isnull().sum()

author                     21417
published                  21417
title                          0
text                          46
language                   21418
site_url                   21418
main_img_url               21418
type                       21418
label                      21418
title_without_stopwords    21419
text_without_stopwords     21467
hasImage                   21418
class                          0
subject                     2096
date                        2096
dtype: int64

In [19]:
df = marge.drop(["text","subject","date","author","published","language","site_url","main_img_url","type","label","title_without_stopwords","text_without_stopwords","hasImage"],axis=1)

In [20]:
df.isnull().sum()

title    0
class    0
dtype: int64

In [21]:
df = df.sample(frac = 1)

In [22]:
df.head()

title  class
6548   U.S. House Republicans weaken ethics body as t...      1
175    looking beyond november th  a song of oligarch...      0
5533   Exclusive - Trump border 'wall' to cost $21.6 ...      1
15367  Lift up your hearts, not your cell phones, pop...      1
445    netflix ceo tvs future includes hallucination ...      0

In [23]:
df.reset_index(inplace = True)
df.drop(["index"], axis = 1, inplace = True)

In [24]:
df.columns

Index(['title', 'class'], dtype='object')

In [25]:
df.head()

title  class
0  U.S. House Republicans weaken ethics body as t...      1
1  looking beyond november th  a song of oligarch...      0
2  Exclusive - Trump border 'wall' to cost $21.6 ...      1
3  Lift up your hearts, not your cell phones, pop...      1
4  netflix ceo tvs future includes hallucination ...      0

In [26]:
def wordopt(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W"," ",text) 
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)    
    return text

In [28]:
df["title"] = df["title"].apply(wordopt)

In [29]:
x = df["title"]
y = df["class"]

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30)

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [32]:
vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
LR = LogisticRegression()
LR.fit(xv_train,y_train)

LogisticRegression()

Logistic Regression()

In [35]:
pred_lr=LR.predict(xv_test)

In [36]:
LR.score(xv_test, y_test)

0.9478310178622058

In [37]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.92      0.45      0.61       627
           1       0.95      1.00      0.97      6427

    accuracy                           0.95      7054
   macro avg       0.94      0.72      0.79      7054
weighted avg       0.95      0.95      0.94      7054



# Decision Tree

In [38]:
from sklearn.tree import DecisionTreeClassifier

In [39]:
DT = DecisionTreeClassifier()
DT.fit(xv_train, y_train)

DecisionTreeClassifier()

DecisionTreeClassifier()

In [40]:
pred_dt = DT.predict(xv_test)

In [41]:
DT.score(xv_test, y_test)

0.9347887723277573

In [42]:
print(classification_report(y_test, pred_dt))

              precision    recall  f1-score   support

           0       0.65      0.59      0.62       627
           1       0.96      0.97      0.96      6427

    accuracy                           0.93      7054
   macro avg       0.80      0.78      0.79      7054
weighted avg       0.93      0.93      0.93      7054



In [43]:
y_pred = DT.predict(xv_test)

In [46]:
print(confusion_matrix(y_test, y_pred)) 

[[ 368  259]
 [ 201 6226]]


In [47]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))        #error
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.0652112276722427
Mean Squared Error: 0.0652112276722427
Root Mean Squared Error: 0.255364891228694


# Naive Bayes

In [48]:
from sklearn.naive_bayes import BernoulliNB

In [49]:
BNB = BernoulliNB()

In [50]:
BNB.fit(xv_train, y_train)

BernoulliNB()

In [51]:
pred_bnb = BNB.predict(xv_test)

In [52]:
BNB.score(xv_test,y_test)

0.9407428409413099

In [53]:
print(classification_report(y_test, pred_bnb))

              precision    recall  f1-score   support

           0       0.97      0.34      0.51       627
           1       0.94      1.00      0.97      6427

    accuracy                           0.94      7054
   macro avg       0.95      0.67      0.74      7054
weighted avg       0.94      0.94      0.93      7054



In [54]:
print(confusion_matrix(y_test, pred_bnb)) 

[[ 216  411]
 [   7 6420]]


In [55]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_bnb))       
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_bnb))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_bnb)))

Mean Absolute Error: 0.059257159058690105
Mean Squared Error: 0.059257159058690105
Root Mean Squared Error: 0.2434279340147513


# K Nearest Neighbor

In [56]:
from sklearn.neighbors import KNeighborsClassifier

In [57]:
ng = KNeighborsClassifier()
ng.fit(xv_test, y_test)

KNeighborsClassifier()

In [58]:
pred_knn = ng.predict(xv_test)

In [59]:
ng.score(xv_test,y_test)

0.9367734618656082

In [60]:
print(classification_report(y_test, pred_knn))  

              precision    recall  f1-score   support

           0       0.58      1.00      0.74       627
           1       1.00      0.93      0.96      6427

    accuracy                           0.94      7054
   macro avg       0.79      0.96      0.85      7054
weighted avg       0.96      0.94      0.94      7054



In [61]:
print(confusion_matrix(y_test, pred_knn))   

[[ 625    2]
 [ 444 5983]]


In [62]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_knn))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_knn))               
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_knn)))

Mean Absolute Error: 0.06322653813439183
Mean Squared Error: 0.06322653813439183
Root Mean Squared Error: 0.2514488777751689


# SVM

In [63]:
from sklearn.svm import LinearSVC

In [64]:
ls = LinearSVC()

In [65]:
ls.fit(xv_test, y_test)

LinearSVC()

In [66]:
pred_ls = ls.predict(xv_test)

In [67]:
ls.score(xv_test,y_test)

0.9971647292316416

In [68]:
print(classification_report(y_test, pred_ls))

              precision    recall  f1-score   support

           0       1.00      0.97      0.98       627
           1       1.00      1.00      1.00      6427

    accuracy                           1.00      7054
   macro avg       1.00      0.98      0.99      7054
weighted avg       1.00      1.00      1.00      7054



In [69]:
print(confusion_matrix(y_test, pred_ls))

[[ 608   19]
 [   1 6426]]


In [70]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_ls))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_ls))                
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_ls)))

Mean Absolute Error: 0.002835270768358378
Mean Squared Error: 0.002835270768358378
Root Mean Squared Error: 0.05324726066529975


# ANN

In [71]:
from sklearn.neural_network import MLPClassifier

In [72]:
ann = MLPClassifier()

In [73]:
ann.fit(xv_test, y_test)

MLPClassifier()

In [74]:
pred_ann = ann.predict(xv_test)

In [75]:
ann.score(xv_test,y_test)

1.0

In [76]:
print(classification_report(y_test, pred_ann)) 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       627
           1       1.00      1.00      1.00      6427

    accuracy                           1.00      7054
   macro avg       1.00      1.00      1.00      7054
weighted avg       1.00      1.00      1.00      7054



In [77]:
print(confusion_matrix(y_test, pred_ann)) 

[[ 627    0]
 [   0 6427]]


In [78]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_ann))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_ann))                 #error
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_ann)))

Mean Absolute Error: 0.0
Mean Squared Error: 0.0
Root Mean Squared Error: 0.0
